export const FETCH_BY_GENRE_SUCCESS = 'FETCH_BY_GENRE_SUCCESS';
export const FETCH_BY_GENRE_FAILURE='FETCH_BY_GENRE_FAILURE';
export const FETCH_BY_GENRE_STARTED='FETCH_BY_GENRE_STARTED';
export const OPEN_MODAL_BY_TYPE='OPEN_MODAL_BY_TYPE';
export const CLOSE_MODAL_BY_TYPE='CLOSE_MODAL_BY_TYPE';
export const CHANGE_INPUT_VALUE='CHANGE_INPUT_VALUE';
export const RESET_VALUES='RESET_VALUES';
export const CHANGE_CHECKBOX_VALUES='CHANGE_CHECKBOX_VALUES';
